name: 42sh

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make

      - name: Compilation
        run: make re

      - name: Check binary exists
        run: test -f ./42sh

      - name: Test basic commands
        run: |
          echo "ls" | ./42sh
          echo "pwd" | ./42sh
          echo "env" | ./42sh
          echo "ls | wc -l" | ./42sh
          echo "ls ; pwd" | ./42sh
          echo "setenv CPE 42sh" | ./42sh
          echo "cd /tmp ; pwd" | ./42sh
          echo "ls && ls -l" | ./42sh
          echo "ls && cv" | ./42sh
          echo "&&" | ./42sh
          echo "cv && ls" | ./42sh
          echo "echo "'salut'"" | ./42sh
          echo "$HOME" | ./42sh
          echo 'azerty' | ./42sh
          echo "/$HOME" | ./42sh
          echo '"azerty"' | ./42sh
          echo "ln && ls -l || cat Makefile" | ./42sh
          echo "latest && ls -l || cat Makefile" | ./42sh
          echo "ls && ls -l || cat Makefile" | ./42sh
          echo "ml && ls -n"
          echo "touch test1.txt" | ./42sh
          echo "touch test2.txt" | ./42sh
          echo "touch test3.txt" | ./42sh
          echo "ls *.txt" | ./42sh
          echo "ls test?.txt" | ./42sh
          echo "ls [a-z]*" | ./42sh
          echo "ls [A-Z]*" | ./42sh
          echo "ls [!A-Z]*" | ./42sh
          echo "ls test[!1].txt" | ./42sh
          echo "ls test[!1-2].txt" | ./42sh
          echo "rm *.txt" | ./42sh